name: phs_mobile
description: The Penn High School&#x27;s mobile app for Android and iOS

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^0.4.0
  url_launcher: ^3.0.3
  cupertino_icons: ^0.1.0
  english_words: ^3.1.0
  flutter_launcher_icons: "^0.6.1"
  firebase_messaging: ^2.0.3
  cloud_firestore: ^0.8.2
  http: ^0.12.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/penniconround.png"

flutter:
  uses-material-design: true
  assets:

    - images/abouticon.png
    - images/phoneicon.png
    - images/getconnectedicon.png
    - images/athleticsicon.png
    - images/background.png
    - images/calendaricon.png
    - images/clubsicon.png
    - images/contactusicon.png
    - images/counseling.png
    - images/fineartsicon.png
    - images/keyicon.png
    - images/newsicon.png
    - images/pennwebsite.png
    - images/sapicon.png
    - images/splashscreen.png
    - images/academicsicon.png

